name: Release on Merge to Main

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main branch
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  registry-url: 'https://registry.npmjs.org'
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run build
              run: pnpm run build
            - name: Run tests
              run: pnpm run test

            - name: Get version from package.json
              id: get-version
              run: |
                  version=$(jq -r .version package.json)
                  echo "version=$version" >> $GITHUB_ENV
                  echo "Release version: $version"

            - name: Make get_changelog.sh executable
              run: chmod +x ./get_changelog.sh

            - name: Get release changelog
              id: get-changelog
              run: |
                  changelog=$(./get_changelog.sh ${{ env.version }} | jq -Rs .)
                  echo "changelog=$changelog" >> $GITHUB_ENV

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  tag_name: v${{ env.version }}
                  release_name: 'Release v${{ env.version }}'
                  body: ${{ fromJSON(env.changelog) }}
                  draft: false
                  prerelease: false

            - name: Publish to npm
              run: |
                  pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
